// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_PLAYER_REGISTER.proto

#include "MSG_PLAYER_REGISTER.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
class MSG_PLAYER_REGISTERDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<MSG_PLAYER_REGISTER>
      _instance;
} _MSG_PLAYER_REGISTER_default_instance_;
namespace protobuf_MSG_5fPLAYER_5fREGISTER_2eproto {
void InitDefaultsMSG_PLAYER_REGISTERImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::_MSG_PLAYER_REGISTER_default_instance_;
    new (ptr) ::MSG_PLAYER_REGISTER();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::MSG_PLAYER_REGISTER::InitAsDefaultInstance();
}

void InitDefaultsMSG_PLAYER_REGISTER() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsMSG_PLAYER_REGISTERImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MSG_PLAYER_REGISTER, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MSG_PLAYER_REGISTER, x_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MSG_PLAYER_REGISTER, z_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MSG_PLAYER_REGISTER, ry_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MSG_PLAYER_REGISTER, speed_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MSG_PLAYER_REGISTER, professsional_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::MSG_PLAYER_REGISTER, playerid_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::MSG_PLAYER_REGISTER)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_MSG_PLAYER_REGISTER_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "MSG_PLAYER_REGISTER.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\031MSG_PLAYER_REGISTER.proto\"o\n\023MSG_PLAYE"
      "R_REGISTER\022\t\n\001x\030\001 \001(\005\022\t\n\001z\030\002 \001(\005\022\n\n\002ry\030\003"
      " \001(\005\022\r\n\005speed\030\004 \001(\005\022\025\n\rprofesssional\030\005 \001"
      "(\005\022\020\n\010playerid\030\006 \001(\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 148);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MSG_PLAYER_REGISTER.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MSG_5fPLAYER_5fREGISTER_2eproto

// ===================================================================

void MSG_PLAYER_REGISTER::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int MSG_PLAYER_REGISTER::kXFieldNumber;
const int MSG_PLAYER_REGISTER::kZFieldNumber;
const int MSG_PLAYER_REGISTER::kRyFieldNumber;
const int MSG_PLAYER_REGISTER::kSpeedFieldNumber;
const int MSG_PLAYER_REGISTER::kProfesssionalFieldNumber;
const int MSG_PLAYER_REGISTER::kPlayeridFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

MSG_PLAYER_REGISTER::MSG_PLAYER_REGISTER()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_MSG_5fPLAYER_5fREGISTER_2eproto::InitDefaultsMSG_PLAYER_REGISTER();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:MSG_PLAYER_REGISTER)
}
MSG_PLAYER_REGISTER::MSG_PLAYER_REGISTER(const MSG_PLAYER_REGISTER& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&x_, &from.x_,
    static_cast<size_t>(reinterpret_cast<char*>(&playerid_) -
    reinterpret_cast<char*>(&x_)) + sizeof(playerid_));
  // @@protoc_insertion_point(copy_constructor:MSG_PLAYER_REGISTER)
}

void MSG_PLAYER_REGISTER::SharedCtor() {
  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&playerid_) -
      reinterpret_cast<char*>(&x_)) + sizeof(playerid_));
  _cached_size_ = 0;
}

MSG_PLAYER_REGISTER::~MSG_PLAYER_REGISTER() {
  // @@protoc_insertion_point(destructor:MSG_PLAYER_REGISTER)
  SharedDtor();
}

void MSG_PLAYER_REGISTER::SharedDtor() {
}

void MSG_PLAYER_REGISTER::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MSG_PLAYER_REGISTER::descriptor() {
  ::protobuf_MSG_5fPLAYER_5fREGISTER_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MSG_5fPLAYER_5fREGISTER_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const MSG_PLAYER_REGISTER& MSG_PLAYER_REGISTER::default_instance() {
  ::protobuf_MSG_5fPLAYER_5fREGISTER_2eproto::InitDefaultsMSG_PLAYER_REGISTER();
  return *internal_default_instance();
}

MSG_PLAYER_REGISTER* MSG_PLAYER_REGISTER::New(::google::protobuf::Arena* arena) const {
  MSG_PLAYER_REGISTER* n = new MSG_PLAYER_REGISTER;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void MSG_PLAYER_REGISTER::Clear() {
// @@protoc_insertion_point(message_clear_start:MSG_PLAYER_REGISTER)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&x_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&playerid_) -
      reinterpret_cast<char*>(&x_)) + sizeof(playerid_));
  _internal_metadata_.Clear();
}

bool MSG_PLAYER_REGISTER::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:MSG_PLAYER_REGISTER)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 x = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &x_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 z = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &z_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 ry = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &ry_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 speed = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &speed_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 professsional = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &professsional_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 playerid = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &playerid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:MSG_PLAYER_REGISTER)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:MSG_PLAYER_REGISTER)
  return false;
#undef DO_
}

void MSG_PLAYER_REGISTER::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:MSG_PLAYER_REGISTER)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->x(), output);
  }

  // int32 z = 2;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->z(), output);
  }

  // int32 ry = 3;
  if (this->ry() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->ry(), output);
  }

  // int32 speed = 4;
  if (this->speed() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(4, this->speed(), output);
  }

  // int32 professsional = 5;
  if (this->professsional() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->professsional(), output);
  }

  // int32 playerid = 6;
  if (this->playerid() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->playerid(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:MSG_PLAYER_REGISTER)
}

::google::protobuf::uint8* MSG_PLAYER_REGISTER::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:MSG_PLAYER_REGISTER)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->x(), target);
  }

  // int32 z = 2;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->z(), target);
  }

  // int32 ry = 3;
  if (this->ry() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->ry(), target);
  }

  // int32 speed = 4;
  if (this->speed() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(4, this->speed(), target);
  }

  // int32 professsional = 5;
  if (this->professsional() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->professsional(), target);
  }

  // int32 playerid = 6;
  if (this->playerid() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->playerid(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:MSG_PLAYER_REGISTER)
  return target;
}

size_t MSG_PLAYER_REGISTER::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:MSG_PLAYER_REGISTER)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 x = 1;
  if (this->x() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->x());
  }

  // int32 z = 2;
  if (this->z() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->z());
  }

  // int32 ry = 3;
  if (this->ry() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->ry());
  }

  // int32 speed = 4;
  if (this->speed() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->speed());
  }

  // int32 professsional = 5;
  if (this->professsional() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->professsional());
  }

  // int32 playerid = 6;
  if (this->playerid() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->playerid());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MSG_PLAYER_REGISTER::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:MSG_PLAYER_REGISTER)
  GOOGLE_DCHECK_NE(&from, this);
  const MSG_PLAYER_REGISTER* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const MSG_PLAYER_REGISTER>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:MSG_PLAYER_REGISTER)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:MSG_PLAYER_REGISTER)
    MergeFrom(*source);
  }
}

void MSG_PLAYER_REGISTER::MergeFrom(const MSG_PLAYER_REGISTER& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:MSG_PLAYER_REGISTER)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.ry() != 0) {
    set_ry(from.ry());
  }
  if (from.speed() != 0) {
    set_speed(from.speed());
  }
  if (from.professsional() != 0) {
    set_professsional(from.professsional());
  }
  if (from.playerid() != 0) {
    set_playerid(from.playerid());
  }
}

void MSG_PLAYER_REGISTER::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:MSG_PLAYER_REGISTER)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MSG_PLAYER_REGISTER::CopyFrom(const MSG_PLAYER_REGISTER& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:MSG_PLAYER_REGISTER)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MSG_PLAYER_REGISTER::IsInitialized() const {
  return true;
}

void MSG_PLAYER_REGISTER::Swap(MSG_PLAYER_REGISTER* other) {
  if (other == this) return;
  InternalSwap(other);
}
void MSG_PLAYER_REGISTER::InternalSwap(MSG_PLAYER_REGISTER* other) {
  using std::swap;
  swap(x_, other->x_);
  swap(z_, other->z_);
  swap(ry_, other->ry_);
  swap(speed_, other->speed_);
  swap(professsional_, other->professsional_);
  swap(playerid_, other->playerid_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata MSG_PLAYER_REGISTER::GetMetadata() const {
  protobuf_MSG_5fPLAYER_5fREGISTER_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_MSG_5fPLAYER_5fREGISTER_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
