// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MSG_PLAYER_MOVE.proto

#ifndef PROTOBUF_MSG_5fPLAYER_5fMOVE_2eproto__INCLUDED
#define PROTOBUF_MSG_5fPLAYER_5fMOVE_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_MSG_5fPLAYER_5fMOVE_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsMSG_PLAYER_MOVEImpl();
void InitDefaultsMSG_PLAYER_MOVE();
inline void InitDefaults() {
  InitDefaultsMSG_PLAYER_MOVE();
}
}  // namespace protobuf_MSG_5fPLAYER_5fMOVE_2eproto
class MSG_PLAYER_MOVE;
class MSG_PLAYER_MOVEDefaultTypeInternal;
extern MSG_PLAYER_MOVEDefaultTypeInternal _MSG_PLAYER_MOVE_default_instance_;

// ===================================================================

class MSG_PLAYER_MOVE : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:MSG_PLAYER_MOVE) */ {
 public:
  MSG_PLAYER_MOVE();
  virtual ~MSG_PLAYER_MOVE();

  MSG_PLAYER_MOVE(const MSG_PLAYER_MOVE& from);

  inline MSG_PLAYER_MOVE& operator=(const MSG_PLAYER_MOVE& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  MSG_PLAYER_MOVE(MSG_PLAYER_MOVE&& from) noexcept
    : MSG_PLAYER_MOVE() {
    *this = ::std::move(from);
  }

  inline MSG_PLAYER_MOVE& operator=(MSG_PLAYER_MOVE&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const MSG_PLAYER_MOVE& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const MSG_PLAYER_MOVE* internal_default_instance() {
    return reinterpret_cast<const MSG_PLAYER_MOVE*>(
               &_MSG_PLAYER_MOVE_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(MSG_PLAYER_MOVE* other);
  friend void swap(MSG_PLAYER_MOVE& a, MSG_PLAYER_MOVE& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline MSG_PLAYER_MOVE* New() const PROTOBUF_FINAL { return New(NULL); }

  MSG_PLAYER_MOVE* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const MSG_PLAYER_MOVE& from);
  void MergeFrom(const MSG_PLAYER_MOVE& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(MSG_PLAYER_MOVE* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // int32 x = 1;
  void clear_x();
  static const int kXFieldNumber = 1;
  ::google::protobuf::int32 x() const;
  void set_x(::google::protobuf::int32 value);

  // int32 z = 2;
  void clear_z();
  static const int kZFieldNumber = 2;
  ::google::protobuf::int32 z() const;
  void set_z(::google::protobuf::int32 value);

  // int32 ry = 3;
  void clear_ry();
  static const int kRyFieldNumber = 3;
  ::google::protobuf::int32 ry() const;
  void set_ry(::google::protobuf::int32 value);

  // int32 playerid = 4;
  void clear_playerid();
  static const int kPlayeridFieldNumber = 4;
  ::google::protobuf::int32 playerid() const;
  void set_playerid(::google::protobuf::int32 value);

  // int32 state = 5;
  void clear_state();
  static const int kStateFieldNumber = 5;
  ::google::protobuf::int32 state() const;
  void set_state(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:MSG_PLAYER_MOVE)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::int32 x_;
  ::google::protobuf::int32 z_;
  ::google::protobuf::int32 ry_;
  ::google::protobuf::int32 playerid_;
  ::google::protobuf::int32 state_;
  mutable int _cached_size_;
  friend struct ::protobuf_MSG_5fPLAYER_5fMOVE_2eproto::TableStruct;
  friend void ::protobuf_MSG_5fPLAYER_5fMOVE_2eproto::InitDefaultsMSG_PLAYER_MOVEImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// MSG_PLAYER_MOVE

// int32 x = 1;
inline void MSG_PLAYER_MOVE::clear_x() {
  x_ = 0;
}
inline ::google::protobuf::int32 MSG_PLAYER_MOVE::x() const {
  // @@protoc_insertion_point(field_get:MSG_PLAYER_MOVE.x)
  return x_;
}
inline void MSG_PLAYER_MOVE::set_x(::google::protobuf::int32 value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:MSG_PLAYER_MOVE.x)
}

// int32 z = 2;
inline void MSG_PLAYER_MOVE::clear_z() {
  z_ = 0;
}
inline ::google::protobuf::int32 MSG_PLAYER_MOVE::z() const {
  // @@protoc_insertion_point(field_get:MSG_PLAYER_MOVE.z)
  return z_;
}
inline void MSG_PLAYER_MOVE::set_z(::google::protobuf::int32 value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:MSG_PLAYER_MOVE.z)
}

// int32 ry = 3;
inline void MSG_PLAYER_MOVE::clear_ry() {
  ry_ = 0;
}
inline ::google::protobuf::int32 MSG_PLAYER_MOVE::ry() const {
  // @@protoc_insertion_point(field_get:MSG_PLAYER_MOVE.ry)
  return ry_;
}
inline void MSG_PLAYER_MOVE::set_ry(::google::protobuf::int32 value) {
  
  ry_ = value;
  // @@protoc_insertion_point(field_set:MSG_PLAYER_MOVE.ry)
}

// int32 playerid = 4;
inline void MSG_PLAYER_MOVE::clear_playerid() {
  playerid_ = 0;
}
inline ::google::protobuf::int32 MSG_PLAYER_MOVE::playerid() const {
  // @@protoc_insertion_point(field_get:MSG_PLAYER_MOVE.playerid)
  return playerid_;
}
inline void MSG_PLAYER_MOVE::set_playerid(::google::protobuf::int32 value) {
  
  playerid_ = value;
  // @@protoc_insertion_point(field_set:MSG_PLAYER_MOVE.playerid)
}

// int32 state = 5;
inline void MSG_PLAYER_MOVE::clear_state() {
  state_ = 0;
}
inline ::google::protobuf::int32 MSG_PLAYER_MOVE::state() const {
  // @@protoc_insertion_point(field_get:MSG_PLAYER_MOVE.state)
  return state_;
}
inline void MSG_PLAYER_MOVE::set_state(::google::protobuf::int32 value) {
  
  state_ = value;
  // @@protoc_insertion_point(field_set:MSG_PLAYER_MOVE.state)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_MSG_5fPLAYER_5fMOVE_2eproto__INCLUDED
