// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Msg_To_And_From_DB.proto

#ifndef PROTOBUF_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto__INCLUDED
#define PROTOBUF_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsDbReq_User_AuthImpl();
void InitDefaultsDbReq_User_Auth();
void InitDefaultsDbRep_User_AuthImpl();
void InitDefaultsDbRep_User_Auth();
inline void InitDefaults() {
  InitDefaultsDbReq_User_Auth();
  InitDefaultsDbRep_User_Auth();
}
}  // namespace protobuf_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto
class DbRep_User_Auth;
class DbRep_User_AuthDefaultTypeInternal;
extern DbRep_User_AuthDefaultTypeInternal _DbRep_User_Auth_default_instance_;
class DbReq_User_Auth;
class DbReq_User_AuthDefaultTypeInternal;
extern DbReq_User_AuthDefaultTypeInternal _DbReq_User_Auth_default_instance_;

// ===================================================================

class DbReq_User_Auth : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DbReq_User_Auth) */ {
 public:
  DbReq_User_Auth();
  virtual ~DbReq_User_Auth();

  DbReq_User_Auth(const DbReq_User_Auth& from);

  inline DbReq_User_Auth& operator=(const DbReq_User_Auth& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DbReq_User_Auth(DbReq_User_Auth&& from) noexcept
    : DbReq_User_Auth() {
    *this = ::std::move(from);
  }

  inline DbReq_User_Auth& operator=(DbReq_User_Auth&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DbReq_User_Auth& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DbReq_User_Auth* internal_default_instance() {
    return reinterpret_cast<const DbReq_User_Auth*>(
               &_DbReq_User_Auth_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(DbReq_User_Auth* other);
  friend void swap(DbReq_User_Auth& a, DbReq_User_Auth& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DbReq_User_Auth* New() const PROTOBUF_FINAL { return New(NULL); }

  DbReq_User_Auth* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DbReq_User_Auth& from);
  void MergeFrom(const DbReq_User_Auth& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DbReq_User_Auth* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string hashedUsrId = 1;
  void clear_hashedusrid();
  static const int kHashedUsrIdFieldNumber = 1;
  const ::std::string& hashedusrid() const;
  void set_hashedusrid(const ::std::string& value);
  #if LANG_CXX11
  void set_hashedusrid(::std::string&& value);
  #endif
  void set_hashedusrid(const char* value);
  void set_hashedusrid(const char* value, size_t size);
  ::std::string* mutable_hashedusrid();
  ::std::string* release_hashedusrid();
  void set_allocated_hashedusrid(::std::string* hashedusrid);

  // string hashedUsrPwd = 2;
  void clear_hashedusrpwd();
  static const int kHashedUsrPwdFieldNumber = 2;
  const ::std::string& hashedusrpwd() const;
  void set_hashedusrpwd(const ::std::string& value);
  #if LANG_CXX11
  void set_hashedusrpwd(::std::string&& value);
  #endif
  void set_hashedusrpwd(const char* value);
  void set_hashedusrpwd(const char* value, size_t size);
  ::std::string* mutable_hashedusrpwd();
  ::std::string* release_hashedusrpwd();
  void set_allocated_hashedusrpwd(::std::string* hashedusrpwd);

  // @@protoc_insertion_point(class_scope:DbReq_User_Auth)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr hashedusrid_;
  ::google::protobuf::internal::ArenaStringPtr hashedusrpwd_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto::InitDefaultsDbReq_User_AuthImpl();
};
// -------------------------------------------------------------------

class DbRep_User_Auth : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:DbRep_User_Auth) */ {
 public:
  DbRep_User_Auth();
  virtual ~DbRep_User_Auth();

  DbRep_User_Auth(const DbRep_User_Auth& from);

  inline DbRep_User_Auth& operator=(const DbRep_User_Auth& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DbRep_User_Auth(DbRep_User_Auth&& from) noexcept
    : DbRep_User_Auth() {
    *this = ::std::move(from);
  }

  inline DbRep_User_Auth& operator=(DbRep_User_Auth&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DbRep_User_Auth& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DbRep_User_Auth* internal_default_instance() {
    return reinterpret_cast<const DbRep_User_Auth*>(
               &_DbRep_User_Auth_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(DbRep_User_Auth* other);
  friend void swap(DbRep_User_Auth& a, DbRep_User_Auth& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DbRep_User_Auth* New() const PROTOBUF_FINAL { return New(NULL); }

  DbRep_User_Auth* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DbRep_User_Auth& from);
  void MergeFrom(const DbRep_User_Auth& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DbRep_User_Auth* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bool isUserVerified = 1;
  void clear_isuserverified();
  static const int kIsUserVerifiedFieldNumber = 1;
  bool isuserverified() const;
  void set_isuserverified(bool value);

  // int32 errCode = 2;
  void clear_errcode();
  static const int kErrCodeFieldNumber = 2;
  ::google::protobuf::int32 errcode() const;
  void set_errcode(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:DbRep_User_Auth)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool isuserverified_;
  ::google::protobuf::int32 errcode_;
  mutable int _cached_size_;
  friend struct ::protobuf_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto::TableStruct;
  friend void ::protobuf_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto::InitDefaultsDbRep_User_AuthImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DbReq_User_Auth

// string hashedUsrId = 1;
inline void DbReq_User_Auth::clear_hashedusrid() {
  hashedusrid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DbReq_User_Auth::hashedusrid() const {
  // @@protoc_insertion_point(field_get:DbReq_User_Auth.hashedUsrId)
  return hashedusrid_.GetNoArena();
}
inline void DbReq_User_Auth::set_hashedusrid(const ::std::string& value) {
  
  hashedusrid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DbReq_User_Auth.hashedUsrId)
}
#if LANG_CXX11
inline void DbReq_User_Auth::set_hashedusrid(::std::string&& value) {
  
  hashedusrid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DbReq_User_Auth.hashedUsrId)
}
#endif
inline void DbReq_User_Auth::set_hashedusrid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hashedusrid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DbReq_User_Auth.hashedUsrId)
}
inline void DbReq_User_Auth::set_hashedusrid(const char* value, size_t size) {
  
  hashedusrid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DbReq_User_Auth.hashedUsrId)
}
inline ::std::string* DbReq_User_Auth::mutable_hashedusrid() {
  
  // @@protoc_insertion_point(field_mutable:DbReq_User_Auth.hashedUsrId)
  return hashedusrid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DbReq_User_Auth::release_hashedusrid() {
  // @@protoc_insertion_point(field_release:DbReq_User_Auth.hashedUsrId)
  
  return hashedusrid_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DbReq_User_Auth::set_allocated_hashedusrid(::std::string* hashedusrid) {
  if (hashedusrid != NULL) {
    
  } else {
    
  }
  hashedusrid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hashedusrid);
  // @@protoc_insertion_point(field_set_allocated:DbReq_User_Auth.hashedUsrId)
}

// string hashedUsrPwd = 2;
inline void DbReq_User_Auth::clear_hashedusrpwd() {
  hashedusrpwd_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& DbReq_User_Auth::hashedusrpwd() const {
  // @@protoc_insertion_point(field_get:DbReq_User_Auth.hashedUsrPwd)
  return hashedusrpwd_.GetNoArena();
}
inline void DbReq_User_Auth::set_hashedusrpwd(const ::std::string& value) {
  
  hashedusrpwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:DbReq_User_Auth.hashedUsrPwd)
}
#if LANG_CXX11
inline void DbReq_User_Auth::set_hashedusrpwd(::std::string&& value) {
  
  hashedusrpwd_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:DbReq_User_Auth.hashedUsrPwd)
}
#endif
inline void DbReq_User_Auth::set_hashedusrpwd(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  hashedusrpwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:DbReq_User_Auth.hashedUsrPwd)
}
inline void DbReq_User_Auth::set_hashedusrpwd(const char* value, size_t size) {
  
  hashedusrpwd_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:DbReq_User_Auth.hashedUsrPwd)
}
inline ::std::string* DbReq_User_Auth::mutable_hashedusrpwd() {
  
  // @@protoc_insertion_point(field_mutable:DbReq_User_Auth.hashedUsrPwd)
  return hashedusrpwd_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* DbReq_User_Auth::release_hashedusrpwd() {
  // @@protoc_insertion_point(field_release:DbReq_User_Auth.hashedUsrPwd)
  
  return hashedusrpwd_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void DbReq_User_Auth::set_allocated_hashedusrpwd(::std::string* hashedusrpwd) {
  if (hashedusrpwd != NULL) {
    
  } else {
    
  }
  hashedusrpwd_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), hashedusrpwd);
  // @@protoc_insertion_point(field_set_allocated:DbReq_User_Auth.hashedUsrPwd)
}

// -------------------------------------------------------------------

// DbRep_User_Auth

// bool isUserVerified = 1;
inline void DbRep_User_Auth::clear_isuserverified() {
  isuserverified_ = false;
}
inline bool DbRep_User_Auth::isuserverified() const {
  // @@protoc_insertion_point(field_get:DbRep_User_Auth.isUserVerified)
  return isuserverified_;
}
inline void DbRep_User_Auth::set_isuserverified(bool value) {
  
  isuserverified_ = value;
  // @@protoc_insertion_point(field_set:DbRep_User_Auth.isUserVerified)
}

// int32 errCode = 2;
inline void DbRep_User_Auth::clear_errcode() {
  errcode_ = 0;
}
inline ::google::protobuf::int32 DbRep_User_Auth::errcode() const {
  // @@protoc_insertion_point(field_get:DbRep_User_Auth.errCode)
  return errcode_;
}
inline void DbRep_User_Auth::set_errcode(::google::protobuf::int32 value) {
  
  errcode_ = value;
  // @@protoc_insertion_point(field_set:DbRep_User_Auth.errCode)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_Msg_5fTo_5fAnd_5fFrom_5fDB_2eproto__INCLUDED
