// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgID.proto

#include "MsgID.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace protobuf_MsgID_2eproto {
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors[1];
const ::google::protobuf::uint32 TableStruct::offsets[1] = {};
static const ::google::protobuf::internal::MigrationSchema* schemas = NULL;
static const ::google::protobuf::Message* const* file_default_instances = NULL;

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "MsgID.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      NULL, file_level_enum_descriptors, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\013MsgID.proto*\241\003\n\005MSGID\022\r\n\tMSG_BEGIN\020\000\022\020"
      "\n\013MSG_TEST_ID\020\355\007\022\027\n\022MSG_PLAYER_MOVE_ID\020\356"
      "\007\022\031\n\024MSG_PLAYER_ATTACK_ID\020\357\007\022\032\n\025MSG_PLAY"
      "ER_REGISTE_ID\020\360\007\022\025\n\020MSG_PLAYER_LOGIN\020\217N\022"
      "\021\n\014MSG_ITEM_ADD\020\220N\022\024\n\017MSG_ITEM_REMOVE\020\221N"
      "\022\024\n\017MSG_PLAYER_FIND\020\222N\022\026\n\021MSG_RANKLIST_S"
      "HOW\020\223N\022\032\n\025MSG_LOGIN_AUTH_PASSED\020\224N\022\032\n\025MS"
      "G_LOGIN_AUTH_FAILED\020\225N\022\031\n\024MSG_LOGIN_REQU"
      "EST_DB\020\226N\022\034\n\027MSG_LOGIN_REPLIY_CLIENT\020\227N\022"
      "$\n\037MSG_REQUEST_BAG_ITEMS_FROM_USER\020\230N\022\"\n"
      "\035MSG_REPLY_BAG_ITEMS_FROM_GAME\020\231Nb\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 441);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "MsgID.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_MsgID_2eproto
const ::google::protobuf::EnumDescriptor* MSGID_descriptor() {
  protobuf_MsgID_2eproto::protobuf_AssignDescriptorsOnce();
  return protobuf_MsgID_2eproto::file_level_enum_descriptors[0];
}
bool MSGID_IsValid(int value) {
  switch (value) {
    case 0:
    case 1005:
    case 1006:
    case 1007:
    case 1008:
    case 9999:
    case 10000:
    case 10001:
    case 10002:
    case 10003:
    case 10004:
    case 10005:
    case 10006:
    case 10007:
    case 10008:
    case 10009:
      return true;
    default:
      return false;
  }
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
