// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgID.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MsgID.proto</summary>
public static partial class MsgIDReflection {

  #region Descriptor
  /// <summary>File descriptor for MsgID.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MsgIDReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "CgtNc2dJRC5wcm90byqhAwoFTVNHSUQSDQoJTVNHX0JFR0lOEAASEAoLTVNH",
          "X1RFU1RfSUQQ7QcSFwoSTVNHX1BMQVlFUl9NT1ZFX0lEEO4HEhkKFE1TR19Q",
          "TEFZRVJfQVRUQUNLX0lEEO8HEhoKFU1TR19QTEFZRVJfUkVHSVNURV9JRBDw",
          "BxIVChBNU0dfUExBWUVSX0xPR0lOEI9OEhEKDE1TR19JVEVNX0FERBCQThIU",
          "Cg9NU0dfSVRFTV9SRU1PVkUQkU4SFAoPTVNHX1BMQVlFUl9GSU5EEJJOEhYK",
          "EU1TR19SQU5LTElTVF9TSE9XEJNOEhoKFU1TR19MT0dJTl9BVVRIX1BBU1NF",
          "RBCUThIaChVNU0dfTE9HSU5fQVVUSF9GQUlMRUQQlU4SGQoUTVNHX0xPR0lO",
          "X1JFUVVFU1RfREIQlk4SHAoXTVNHX0xPR0lOX1JFUExJWV9DTElFTlQQl04S",
          "JAofTVNHX1JFUVVFU1RfQkFHX0lURU1TX0ZST01fVVNFUhCYThIiCh1NU0df",
          "UkVQTFlfQkFHX0lURU1TX0ZST01fR0FNRRCZTmIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(new[] {typeof(global::MSGID), }, null));
  }
  #endregion

}
#region Enums
public enum MSGID {
  [pbr::OriginalName("MSG_BEGIN")] MsgBegin = 0,
  [pbr::OriginalName("MSG_TEST_ID")] MsgTestId = 1005,
  [pbr::OriginalName("MSG_PLAYER_MOVE_ID")] MsgPlayerMoveId = 1006,
  [pbr::OriginalName("MSG_PLAYER_ATTACK_ID")] MsgPlayerAttackId = 1007,
  [pbr::OriginalName("MSG_PLAYER_REGISTE_ID")] MsgPlayerRegisteId = 1008,
  [pbr::OriginalName("MSG_PLAYER_LOGIN")] MsgPlayerLogin = 9999,
  [pbr::OriginalName("MSG_ITEM_ADD")] MsgItemAdd = 10000,
  [pbr::OriginalName("MSG_ITEM_REMOVE")] MsgItemRemove = 10001,
  [pbr::OriginalName("MSG_PLAYER_FIND")] MsgPlayerFind = 10002,
  [pbr::OriginalName("MSG_RANKLIST_SHOW")] MsgRanklistShow = 10003,
  [pbr::OriginalName("MSG_LOGIN_AUTH_PASSED")] MsgLoginAuthPassed = 10004,
  [pbr::OriginalName("MSG_LOGIN_AUTH_FAILED")] MsgLoginAuthFailed = 10005,
  [pbr::OriginalName("MSG_LOGIN_REQUEST_DB")] MsgLoginRequestDb = 10006,
  [pbr::OriginalName("MSG_LOGIN_REPLIY_CLIENT")] MsgLoginRepliyClient = 10007,
  [pbr::OriginalName("MSG_REQUEST_BAG_ITEMS_FROM_USER")] MsgRequestBagItemsFromUser = 10008,
  [pbr::OriginalName("MSG_REPLY_BAG_ITEMS_FROM_GAME")] MsgReplyBagItemsFromGame = 10009,
}

#endregion


#endregion Designer generated code
