// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MSG_PLAYER_REGISTER.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from MSG_PLAYER_REGISTER.proto</summary>
public static partial class MSGPLAYERREGISTERReflection {

  #region Descriptor
  /// <summary>File descriptor for MSG_PLAYER_REGISTER.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MSGPLAYERREGISTERReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChlNU0dfUExBWUVSX1JFR0lTVEVSLnByb3RvIm8KE01TR19QTEFZRVJfUkVH",
          "SVNURVISCQoBeBgBIAEoBRIJCgF6GAIgASgFEgoKAnJ5GAMgASgFEg0KBXNw",
          "ZWVkGAQgASgFEhUKDXByb2Zlc3NzaW9uYWwYBSABKAUSEAoIcGxheWVyaWQY",
          "BiABKAViBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::MSG_PLAYER_REGISTER), global::MSG_PLAYER_REGISTER.Parser, new[]{ "X", "Z", "Ry", "Speed", "Professsional", "Playerid" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
public sealed partial class MSG_PLAYER_REGISTER : pb::IMessage<MSG_PLAYER_REGISTER> {
  private static readonly pb::MessageParser<MSG_PLAYER_REGISTER> _parser = new pb::MessageParser<MSG_PLAYER_REGISTER>(() => new MSG_PLAYER_REGISTER());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<MSG_PLAYER_REGISTER> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MSGPLAYERREGISTERReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MSG_PLAYER_REGISTER() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MSG_PLAYER_REGISTER(MSG_PLAYER_REGISTER other) : this() {
    x_ = other.x_;
    z_ = other.z_;
    ry_ = other.ry_;
    speed_ = other.speed_;
    professsional_ = other.professsional_;
    playerid_ = other.playerid_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public MSG_PLAYER_REGISTER Clone() {
    return new MSG_PLAYER_REGISTER(this);
  }

  /// <summary>Field number for the "x" field.</summary>
  public const int XFieldNumber = 1;
  private int x_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int X {
    get { return x_; }
    set {
      x_ = value;
    }
  }

  /// <summary>Field number for the "z" field.</summary>
  public const int ZFieldNumber = 2;
  private int z_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Z {
    get { return z_; }
    set {
      z_ = value;
    }
  }

  /// <summary>Field number for the "ry" field.</summary>
  public const int RyFieldNumber = 3;
  private int ry_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Ry {
    get { return ry_; }
    set {
      ry_ = value;
    }
  }

  /// <summary>Field number for the "speed" field.</summary>
  public const int SpeedFieldNumber = 4;
  private int speed_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Speed {
    get { return speed_; }
    set {
      speed_ = value;
    }
  }

  /// <summary>Field number for the "professsional" field.</summary>
  public const int ProfesssionalFieldNumber = 5;
  private int professsional_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Professsional {
    get { return professsional_; }
    set {
      professsional_ = value;
    }
  }

  /// <summary>Field number for the "playerid" field.</summary>
  public const int PlayeridFieldNumber = 6;
  private int playerid_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int Playerid {
    get { return playerid_; }
    set {
      playerid_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as MSG_PLAYER_REGISTER);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(MSG_PLAYER_REGISTER other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (X != other.X) return false;
    if (Z != other.Z) return false;
    if (Ry != other.Ry) return false;
    if (Speed != other.Speed) return false;
    if (Professsional != other.Professsional) return false;
    if (Playerid != other.Playerid) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (X != 0) hash ^= X.GetHashCode();
    if (Z != 0) hash ^= Z.GetHashCode();
    if (Ry != 0) hash ^= Ry.GetHashCode();
    if (Speed != 0) hash ^= Speed.GetHashCode();
    if (Professsional != 0) hash ^= Professsional.GetHashCode();
    if (Playerid != 0) hash ^= Playerid.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (X != 0) {
      output.WriteRawTag(8);
      output.WriteInt32(X);
    }
    if (Z != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(Z);
    }
    if (Ry != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(Ry);
    }
    if (Speed != 0) {
      output.WriteRawTag(32);
      output.WriteInt32(Speed);
    }
    if (Professsional != 0) {
      output.WriteRawTag(40);
      output.WriteInt32(Professsional);
    }
    if (Playerid != 0) {
      output.WriteRawTag(48);
      output.WriteInt32(Playerid);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (X != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
    }
    if (Z != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Z);
    }
    if (Ry != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Ry);
    }
    if (Speed != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Speed);
    }
    if (Professsional != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Professsional);
    }
    if (Playerid != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(Playerid);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(MSG_PLAYER_REGISTER other) {
    if (other == null) {
      return;
    }
    if (other.X != 0) {
      X = other.X;
    }
    if (other.Z != 0) {
      Z = other.Z;
    }
    if (other.Ry != 0) {
      Ry = other.Ry;
    }
    if (other.Speed != 0) {
      Speed = other.Speed;
    }
    if (other.Professsional != 0) {
      Professsional = other.Professsional;
    }
    if (other.Playerid != 0) {
      Playerid = other.Playerid;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          X = input.ReadInt32();
          break;
        }
        case 16: {
          Z = input.ReadInt32();
          break;
        }
        case 24: {
          Ry = input.ReadInt32();
          break;
        }
        case 32: {
          Speed = input.ReadInt32();
          break;
        }
        case 40: {
          Professsional = input.ReadInt32();
          break;
        }
        case 48: {
          Playerid = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
