// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Msg_To_And_From_DB.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from Msg_To_And_From_DB.proto</summary>
public static partial class MsgToAndFromDBReflection {

  #region Descriptor
  /// <summary>File descriptor for Msg_To_And_From_DB.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MsgToAndFromDBReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChhNc2dfVG9fQW5kX0Zyb21fREIucHJvdG8iPAoPRGJSZXFfVXNlcl9BdXRo",
          "EhMKC2hhc2hlZFVzcklkGAEgASgJEhQKDGhhc2hlZFVzclB3ZBgCIAEoCSI6",
          "Cg9EYlJlcF9Vc2VyX0F1dGgSFgoOaXNVc2VyVmVyaWZpZWQYASABKAgSDwoH",
          "ZXJyQ29kZRgCIAEoBWIGcHJvdG8z"));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::DbReq_User_Auth), global::DbReq_User_Auth.Parser, new[]{ "HashedUsrId", "HashedUsrPwd" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::DbRep_User_Auth), global::DbRep_User_Auth.Parser, new[]{ "IsUserVerified", "ErrCode" }, null, null, null)
        }));
  }
  #endregion

}
#region Messages
/// <summary>
/// todo: 改为加盐
/// </summary>
public sealed partial class DbReq_User_Auth : pb::IMessage<DbReq_User_Auth> {
  private static readonly pb::MessageParser<DbReq_User_Auth> _parser = new pb::MessageParser<DbReq_User_Auth>(() => new DbReq_User_Auth());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<DbReq_User_Auth> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MsgToAndFromDBReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DbReq_User_Auth() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DbReq_User_Auth(DbReq_User_Auth other) : this() {
    hashedUsrId_ = other.hashedUsrId_;
    hashedUsrPwd_ = other.hashedUsrPwd_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DbReq_User_Auth Clone() {
    return new DbReq_User_Auth(this);
  }

  /// <summary>Field number for the "hashedUsrId" field.</summary>
  public const int HashedUsrIdFieldNumber = 1;
  private string hashedUsrId_ = "";
  /// <summary>
  /// 哈希后的玩家账号
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string HashedUsrId {
    get { return hashedUsrId_; }
    set {
      hashedUsrId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "hashedUsrPwd" field.</summary>
  public const int HashedUsrPwdFieldNumber = 2;
  private string hashedUsrPwd_ = "";
  /// <summary>
  /// 哈希后的玩家密码
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string HashedUsrPwd {
    get { return hashedUsrPwd_; }
    set {
      hashedUsrPwd_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as DbReq_User_Auth);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(DbReq_User_Auth other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (HashedUsrId != other.HashedUsrId) return false;
    if (HashedUsrPwd != other.HashedUsrPwd) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (HashedUsrId.Length != 0) hash ^= HashedUsrId.GetHashCode();
    if (HashedUsrPwd.Length != 0) hash ^= HashedUsrPwd.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (HashedUsrId.Length != 0) {
      output.WriteRawTag(10);
      output.WriteString(HashedUsrId);
    }
    if (HashedUsrPwd.Length != 0) {
      output.WriteRawTag(18);
      output.WriteString(HashedUsrPwd);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (HashedUsrId.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HashedUsrId);
    }
    if (HashedUsrPwd.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(HashedUsrPwd);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(DbReq_User_Auth other) {
    if (other == null) {
      return;
    }
    if (other.HashedUsrId.Length != 0) {
      HashedUsrId = other.HashedUsrId;
    }
    if (other.HashedUsrPwd.Length != 0) {
      HashedUsrPwd = other.HashedUsrPwd;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 10: {
          HashedUsrId = input.ReadString();
          break;
        }
        case 18: {
          HashedUsrPwd = input.ReadString();
          break;
        }
      }
    }
  }

}

public sealed partial class DbRep_User_Auth : pb::IMessage<DbRep_User_Auth> {
  private static readonly pb::MessageParser<DbRep_User_Auth> _parser = new pb::MessageParser<DbRep_User_Auth>(() => new DbRep_User_Auth());
  private pb::UnknownFieldSet _unknownFields;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<DbRep_User_Auth> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MsgToAndFromDBReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DbRep_User_Auth() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DbRep_User_Auth(DbRep_User_Auth other) : this() {
    isUserVerified_ = other.isUserVerified_;
    errCode_ = other.errCode_;
    _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public DbRep_User_Auth Clone() {
    return new DbRep_User_Auth(this);
  }

  /// <summary>Field number for the "isUserVerified" field.</summary>
  public const int IsUserVerifiedFieldNumber = 1;
  private bool isUserVerified_;
  /// <summary>
  /// 用户数据是否正确
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool IsUserVerified {
    get { return isUserVerified_; }
    set {
      isUserVerified_ = value;
    }
  }

  /// <summary>Field number for the "errCode" field.</summary>
  public const int ErrCodeFieldNumber = 2;
  private int errCode_;
  /// <summary>
  /// GameSpec里的Errcode
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int ErrCode {
    get { return errCode_; }
    set {
      errCode_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as DbRep_User_Auth);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(DbRep_User_Auth other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (IsUserVerified != other.IsUserVerified) return false;
    if (ErrCode != other.ErrCode) return false;
    return Equals(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (IsUserVerified != false) hash ^= IsUserVerified.GetHashCode();
    if (ErrCode != 0) hash ^= ErrCode.GetHashCode();
    if (_unknownFields != null) {
      hash ^= _unknownFields.GetHashCode();
    }
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (IsUserVerified != false) {
      output.WriteRawTag(8);
      output.WriteBool(IsUserVerified);
    }
    if (ErrCode != 0) {
      output.WriteRawTag(16);
      output.WriteInt32(ErrCode);
    }
    if (_unknownFields != null) {
      _unknownFields.WriteTo(output);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (IsUserVerified != false) {
      size += 1 + 1;
    }
    if (ErrCode != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(ErrCode);
    }
    if (_unknownFields != null) {
      size += _unknownFields.CalculateSize();
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(DbRep_User_Auth other) {
    if (other == null) {
      return;
    }
    if (other.IsUserVerified != false) {
      IsUserVerified = other.IsUserVerified;
    }
    if (other.ErrCode != 0) {
      ErrCode = other.ErrCode;
    }
    _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
          break;
        case 8: {
          IsUserVerified = input.ReadBool();
          break;
        }
        case 16: {
          ErrCode = input.ReadInt32();
          break;
        }
      }
    }
  }

}

#endregion


#endregion Designer generated code
